### ISSUE TITLE
Image.reduceRegion: Provide 'geometry' parameter when aggregating over an unbounded image

### ISSUE THREAD

**Issue by makovz** [aazuspan/geeSharpening#4]
Reopening a script of some months ago, now I get the error "Layer error: Image.reduceRegion: Provide 'geometry' parameter when aggregating over an unbounded image"

Thanks in advance

**Comment by aazuspan** [comment]
Hi @makovz, can you share your code? You can probably fix this by clipping your image before sharpening or passing a `geometry` parameter to the sharpening function, but it's hard to say for sure without seeing the script.

**Comment by makovz** [comment]
Hi @aazuspan here you can access the simple code using your library: https://code.earthengine.google.com/9932e89494ec03a7b537e860625d7bfd

I've tried to add the geometry in the application pf your script, but no luck
many thanks in advance

**Comment by aazuspan** [comment]
This ended up being a more complex issue than I thought, but I managed to get it working. Here's a link to [your script that I modified](https://code.earthengine.google.com/0f1acc73a6fb8cc7c70fe1655f31ee63). There's also an issue with selecting the wrong bands, but that should be an easy fix.

I changed two things. First, `roi` is a `FeatureCollection` instead of a `Geometry` which was causing a problem with clipping, so I used `roi.geometry()` instead on line 27. Second, some projection information is lost when you create a composite like `medianTOA`, so you need to add that back to the image using `ee.Image.setDefaultProjection`. You can see that I grabbed projection information from the original images on line 35-37 and added it to the composite on line 41-44. 

Thanks for reporting the issue. Now that I know about the default projection problem with composites, I'll look into handling that automatically with geeSharp.

**Comment by makovz** [comment]
Dear Aron, thanks a lot for your help!
